### ISSUE TITLE
Finalize date of 2nd Rust Hungary Meetup

### ISSUE THREAD

**Issue by flaki** [MozillaHU/rust-hungary#3]
Finalize a date for the first meetup in September based on the below constraints.

Availability:

- [x] **Org. team - Flaki** (@flaki): October 16-18, 23-24(-25), (31)
- [x] **Org. team - Peter** (@peteyy): October 1-31
- [ ] **Talk 1** (@peteyy?):
- [ ] **Talk 2** (@nbaksalyar?): October 1-25
- [ ] **Talk 3** (?):

Please share your availability below in comments so we can finalize the date. Once we finalized the dates we'll continue with locking down a suitable venue in Budapest and decide on the rest of the specific details (including travel and other arrangements).

**Comment by nbaksalyar** [comment]
I'm available September 26-October 25.
Thank you for the invite! :)

**Comment by peteyycz** [comment]
I'm available from September 21! 🚀  Let's do this I'm already HYPED for RUST!! :)))

**Comment by flaki** [comment]
Looking at the date October 24, Tuesday evening.

**Comment by flaki** [comment]
Date finalized and speakers/meetup announced:
* https://www.meetup.com/Rust-Hungary-Meetup/events/244086300/
* http://rust-lang.hu/posts/2017-10-20/meetup-02-mozilla-dev-roadshow.html
