### ISSUE TITLE
Finalize lineup for 2nd Rust Hungary Meetup

### ISSUE THREAD

**Issue by flaki** [MozillaHU/rust-hungary#4]
"[Mozilla Developer Roadshow](https://mzl.la/devroadshow)" Edition

We are planning 3 talks for the first meetup, roughly 2-2.5 hours, with presentations 25-30 minutes each+questions.

Draft lineup below:

- ~Peter Czibik/Szakallas David~ - _moved to November_
- [x] *(in-progress)*  Nikita Baksalyar @nbaksalyar - Exporting Rust: What you need to know about FFI
- [x] *(in-progress)* Nical Silva - Firefox Quantum / WebRender ?
- [x] *(in-progress)* USZeged DSU @dati91 loki04 - WebRender research

Please take time and submit the following items for your talk:
- Talk title (English title mandatory, Hungarian title optional)
- Talk summary/description (2-5 sentences, English description mandatory, Hungarian optional)
- Name of the presenter(s) with headshot/speaker photo
- Contacts/social media (twitter handle, github handle, linkedin profile URL - all optional)
- The language of the talk

The recommended language to present your talk is English. If someone is not comfortable presenting in English, Hungarian language talks are also accepted. All talks will be recorded and shared online, with subtitles in both Hungarian and English.

**Comment by peteyycz** [comment]
@szdavid92 would you like to have a presentation on the second meetup? :)

**Comment by dszakallas** [comment]
when will this meetup happen?

**Comment by peteyycz** [comment]
Mid November I think, right @flaki?

**Comment by nbaksalyar** [comment]
Hey there! Here's my proposal:

**Exporting Rust: What you need to know about FFI**

The world is imperfect and not every program is written in Rust yet, and while we're rewriting everything, we need to deal with this fact somehow. That's where the Foreign Function Interface (or FFI for short) comes into play: it allows programs written in other languages to talk to Rust. It might seem straightforward at first, but the FFI has many non-obvious parts and open questions: how do you deal with ownership and borrowing and how do you use drop flags to deallocate memory and free resources? How do you pass vectors and slices to external functions and back? What is the proper way to work with strings and why do we need CStr and CString? There's no single proper way to solve these problems, but we'll try to find answers in this talk, learning from the hands-on experience.

_Language:_ English
_Contacts:_ @nbaksalyar on Twitter & GitHub

**Comment by flaki** [comment]
Meetup has been announced:
https://www.meetup.com/Rust-Hungary-Meetup/events/244086300/
