### ISSUE TITLE
Finalize 3rd Rust Hungary Meetup

### ISSUE THREAD

**Issue by flaki** [MozillaHU/rust-hungary#6]
2017. november 23., 18:00

- [x] Jan-Erik Rediger (@badboy) - WebAssembly & Rust
- [x] Peter Czibik/Szakallas David @peteyy - Rust in Node ?
- [X] Valentin Gosu (@valenting) - The (hi)story of Rust in Firefox

**Comment by badboy** [comment]
I guess I can't say no anymore. Fine with me!

**Comment by flaki** [comment]
Looking at these potential dates for the meetup:
 - November 23, Thursday evening
 - ~~November 27, Monday evening~~
 - ~~November 28, Tuesday evening~~

**Comment by flaki** [comment]
Date has been decided (Nov. 23.) and all speakers confirmed.
